version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: pv
        target: /var/www/
        volume:
          nocopy: true
    restart: always

volumes:
  pv:
    name: "pv"
    driver: local
    driver_opts:
      type: 'none'
      o: 'size=5G,rw'
      device: '/DockerPV/'
